class_name SpriteLib
extends RefCounted

## Builds SpriteFrames from the exported strips in assets/sprites/.
##
## Those PNGs were generated by replaying the browser build's own canvas
## drawing code, so the sprites here are pixel-identical to the web version —
## same three zombie palettes, same walk/attack/death cycles, same 1px dark
## rim that outlineSprite() stamped so silhouettes read in the dark.

const DIR := "res://assets/sprites/"

## frame counts and cell size per animation, matching makeZombieSet() etc.
const SPEC := {
	"zombie": {"w": 48, "h": 64, "walk": 6, "attack": 2, "death": 4, "pal": 3},
	"crawler": {"w": 48, "h": 34, "walk": 4, "death": 3, "pal": 3},
	"hound": {"w": 56, "h": 40, "walk": 4, "death": 3, "pal": 0},
}

## World height in metres for each type — from the browser build's ZH table.
const HEIGHT := {"zombie": 1.82, "crawler": 0.62, "hound": 0.98}

static var _cache := {}


static func frames_for(kind: String, pal: int) -> SpriteFrames:
	var key := "%s%d" % [kind, pal]
	if _cache.has(key):
		return _cache[key]

	var spec: Dictionary = SPEC[kind]
	var sf := SpriteFrames.new()
	sf.remove_animation("default")

	var prefix := kind + str(pal) if spec.pal > 0 else kind

	_add_strip(sf, "walk", DIR + prefix + "_walk.png", spec.w, spec.h, spec.walk, 8.0, true)

	if spec.has("attack"):
		_add_strip(sf, "attack", DIR + prefix + "_attack.png", spec.w, spec.h, spec.attack, 6.0, true)
	else:
		# Crawlers and hounds reuse the first two walk frames as their swing,
		# exactly as the browser build did (attack: walk.slice(0, 2)).
		_add_strip(sf, "attack", DIR + prefix + "_walk.png", spec.w, spec.h, 2, 6.0, true)

	_add_strip(sf, "death", DIR + prefix + "_death.png", spec.w, spec.h, spec.death, 9.0, false)

	_cache[key] = sf
	return sf


static func _add_strip(sf: SpriteFrames, anim: String, path: String,
		w: int, h: int, count: int, fps: float, loops: bool) -> void:
	sf.add_animation(anim)
	sf.set_animation_speed(anim, fps)
	sf.set_animation_loop(anim, loops)
	if not ResourceLoader.exists(path):
		push_warning("SpriteLib: missing sheet " + path)
		return
	var sheet: Texture2D = load(path)
	for i in count:
		var at := AtlasTexture.new()
		at.atlas = sheet
		at.region = Rect2(i * w, 0, w, h)
		at.filter_clip = true
		sf.add_frame(anim, at)


## Metres-per-pixel so a sprite lands at its correct world height.
static func pixel_size(kind: String) -> float:
	var spec: Dictionary = SPEC[kind]
	return HEIGHT[kind] / float(spec.h)
